name: CI

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:    
    runs-on: ubuntu-latest   
    name: Build and test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2   
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --configuration Release